In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#src = cv2.imread('./data/cells.png', cv2.IMREAD_GRAYSCALE)
cap = cv2.VideoCapture(2)

while True:
    ret, frame = cap.read()

    if not ret:
        break
    
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    th, dst = cv2.threshold(frame, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    print("otsu's threshold:", th)
    #_, dst2 = cv2.threshold(frame, 210, 255, cv2.THRESH_BINARY)

    cv2.imshow('frame', frame)
    cv2.imshow('dst', dst)
    key = cv2.waitKey(1)

    if key == 27:
        break
    elif key == ord(' '):
        cam_mode += 1
        if cam_mode == 3:
            cam_mode = 0

cap.release()
cv2.destroyAllWindows()

'''
_, dst1 = cv2.threshold(src, 100, 255, cv2.THRESH_BINARY)
_, dst2 = cv2.threshold(src, 210, 255, cv2.THRESH_BINARY)

cv2.imshow('src', src)
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()
'''

otsu's threshold: 65.0
otsu's threshold: 143.0
otsu's threshold: 144.0
otsu's threshold: 147.0
otsu's threshold: 147.0
otsu's threshold: 147.0
otsu's threshold: 147.0
otsu's threshold: 146.0
otsu's threshold: 146.0
otsu's threshold: 146.0
otsu's threshold: 146.0
otsu's threshold: 145.0
otsu's threshold: 145.0
otsu's threshold: 145.0
otsu's threshold: 145.0
otsu's threshold: 145.0
otsu's threshold: 145.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 144.0
otsu's threshold: 143.0
otsu's threshold: 143.0
otsu's threshold: 143.0
otsu's threshold: 143.0
otsu's threshold: 142.0
otsu's threshold: 142.0
otsu's threshold: 142.0
otsu's threshold: 142.0
otsu's threshold: 142.0
otsu's threshold: 142.0
otsu's threshold: 141.0
otsu's threshold: 141.0
otsu's threshold: 141.0
otsu's threshold: 141.0
otsu's threshold: 141.0
otsu's threshold: 141.0
otsu's threshold:

"\n_, dst1 = cv2.threshold(src, 100, 255, cv2.THRESH_BINARY)\n_, dst2 = cv2.threshold(src, 210, 255, cv2.THRESH_BINARY)\n\ncv2.imshow('src', src)\ncv2.imshow('dst1', dst1)\ncv2.imshow('dst2', dst2)\ncv2.waitKey()\ncv2.destroyAllWindows()\n"

In [6]:
src = cv2.imread('./data/sudoku.jpg', cv2.IMREAD_GRAYSCALE)

bsize = 201
dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                            cv2.THRESH_BINARY, bsize, 5)

cv2.imshow('dst', dst)
cv2.imshow('src', src)
cv2.namedWindow('dst')

cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
mat = np.array([
    [0, 0, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 1, 0, 0, 1, 0],
    [1, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1, 1, 1, 0],
    [0, 0, 1, 1, 0, 0, 1, 0],
    [0, 0, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]], np.uint8)

cnt, labels = cv2.connectedComponents(mat)

print('sep:', mat, sep='\n')
print('cnt:', cnt)
print('labels:', labels, sep='\n')

sep:
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 1 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 1 1 1 1 0]
 [0 0 1 1 0 0 1 0]
 [0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
cnt: 4
labels:
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 3 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]


In [8]:
src = cv2.imread('./data/keyboard.jpg', cv2.IMREAD_GRAYSCALE)

_, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_OTSU)
cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

for i in range(1, cnt):
    (x, y, w, h, area) = stats[i]

    if area < 20:
        continue

    cv2.rectangle(dst, (x, y, w, h), (0, 255, 255))
    cv2.putText(dst, str(i), (x, y), cv2.FONT_HERSHEY_SIMPLEX,
                0.8, (0,0,255), 1, cv2.LINE_AA)
    
cv2.imshow('src', src)
cv2.imshow('src_bin', src_bin)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
import random

src = cv2.imread('./data/contours.jpg', cv2.IMREAD_GRAYSCALE)

contours, hier = cv2.findContours(src, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

idx = 0
while idx >= 0:
    c = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
    cv2.drawContours(dst, contours, idx, c, 2, cv2.LINE_8, hier)
    idx = hier[0, idx, 0]

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()